# conda environment description for RandoPony package development environment
#
# Create a conda environment for development, testing & documentation
# of the RandoPony package with:
#
#  $ cd RandoPony-tetra
#  $ conda env create -f environment.yaml
#  $ source activate randopony
#  (raondopony)$ pip install --editable .
#
# See the requirements.txt file for an exhaustive list of all of the
# packages installed in the environment and their versions used in
# recent development.

name: randopony

dependencies:
- coverage
#- gdata
- ipython
- pytz
- pytest
- python=3.5
#- supervisor
- sphinx
- pip:
  - celery
  - colander==1.2
  - deform==0.9.9
  - passlib
  - pyramid==1.7.3
  - pyramid-crow
  - pyramid_debugtoolbar
  - pyramid-deform
  - pyramid-mailer
  - pyramid_mako
  - pyramid-tm
  - sqlalchemy
  - transaction
  - zope.sqlalchemy
